### ISSUE TITLE
PyCUDA ERROR when running example script

### ISSUE THREAD

**Issue by wabhijan** [Dad0u/GPUCorrel#1]
When trying to run any script using this library, I get a pyCUDA error.

```
pycuda.driver.CompileError: nvcc preprocessing of C:\Users\<username>\AppData\Local\Temp\tmp67wn3cf9.cu failed
[command: nvcc --preprocess -arch sm_86 -m64 -IC:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\pycuda\cuda C:\Users\<username>\AppData\Local\Temp\tmp67wn3cf9.cu --compiler-options -EP]
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup. 
-------------------------------------------------------------------
A context was still active when the context stack was being        
cleaned up. At this point in our execution, CUDA may already       
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
```
`nvcc --version` returns

```
nvcc: NVIDIA (R) Cuda compiler driver                                                     
Copyright (c) 2005-2023 NVIDIA Corporation                                                                              
Built on Tue_Jun_13_19:42:34_Pacific_Daylight_Time_2023                                                                 
Cuda compilation tools, release 12.2, V12.2.91                                                                          
Build cuda_12.2.r12.2/compiler.32965470_0     
```

**Comment by Dad0u** [comment]
Hello wabhijan,
I suspect this error comes from the PyCUDA installation. Have you tried to run any other PyCUDA program in this environment ? If the environment is known to work, please provide the full traceback to help troubleshoot the issue.

Also, please note that although it may work, GPUCorrel was not tested on Windows, only on Ubuntu.

**Comment by wabhijan** [comment]
I tried running another basic code in PyCUDA and looks like you're right. PyCUDA isn't able to compile.
I don't understand why this is, as I just installed PyCUDA just for this library. I have an NVIDIA GeForce RTX 3090, which is a CUDA-capable GPU.

**Comment by wabhijan** [comment]
UPDATE:
I installed Visual Studio, added paths in environment variables, and tried running some basic code from here: https://documen.tician.de/pycuda/tutorial.html and it seems to compile.
However, the example script still does not run.
Here's the traceback:
```
    [Correl] You set the verbose level to the maximum.
It may help finding bugs or tracking errors but it may also impact the program performance as it will print A LOT of output and add GPU->CPU copies only to print information.
If it is not desired, consider lowering the verbosity: 1 or 2 is a reasonable choice, 0 won't show anything except for errors.
[Correl] Initializing... Master resolution: (1080, 1920) levels: 5 verbosity: 3
    [Correl] Kernel file: gpucorrel/kernels/kernels.cu
  [Stage 0] Initializing with resolution (1080, 1920)
    [Stage 0] Default grid: (60, 34) block (32, 32, 1)
    [Stage 0] Sourcing module
Traceback (most recent call last):
  File "C:\<dir>\GPUCorrel\src\artificial_strain.py", line 30, in <module>
    correl = GPUCorrel((h,w),fields=[x,y,r,exx,eyy,exy2],verbose=3)
  File "C:\<dir>\GPUCorrel\src\gpucorrel\gpucorrel.py", line 328, in __init__
    self.correl.append(Correl_level((self.h[i], self.w[i]),
  File "C:\<dir>\GPUCorrel\src\gpucorrel\gpucorrel_level.py", line 92, in __init__
    self.mod = SourceModule(f.read() % (self.w, self.h, self.fields_count))
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\pycuda\compiler.py", line 355, in __init__
    cubin = compile(
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\pycuda\compiler.py", line 304, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\pycuda\compiler.py", line 154, in compile_plain
    raise CompileError(
pycuda.driver.CompileError: nvcc compilation of C:\Users\<username>\AppData\Local\Temp\tmpgscbb2g6\kernel.cu failed
[command: nvcc --cubin -arch sm_86 -m64 -IC:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\pycuda\cuda kernel.cu]
[stdout:
kernel.cu(16): error: texture is not a template
  texture<float, 0x02, cudaReadModeElementType> tex;
  ^

kernel.cu(18): error: texture is not a template
  texture<float, 0x02, cudaReadModeElementType> tex_d;
  ^

kernel.cu(20): error: texture is not a template
  texture<float, 0x02, cudaReadModeElementType> texMask;
  ^

kernel.cu(31): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
          tex2D(tex, (x+1.5f)/1920, (float)y/1080)
          ^

kernel.cu(32): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
          +tex2D(tex, (x+1.5f)/1920, (y+1.f)/1080)
           ^

kernel.cu(33): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
          -tex2D(tex, (x-.5f)/1920, (float)y/1080)
           ^

kernel.cu(34): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
          -tex2D(tex, (x-.5f)/1920, (y+1.f)/1080)
           ^

kernel.cu(37): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
          tex2D(tex, (float)x/1920, (y+1.5f)/1080)
          ^

kernel.cu(38): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
          +tex2D(tex, (x+1.f)/1920, (y+1.5f)/1080)
           ^

kernel.cu(39): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
          -tex2D(tex, (float)x/1920, (y-.5f)/1080)
           ^

kernel.cu(40): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
          -tex2D(tex, (x+1.f)/1920, (y-.5f)/1080)
           ^

kernel.cu(51): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
      out[idx+w*idy] = tex2D(tex,(float)idx/w,(float)idy/h);
                       ^

kernel.cu(60): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
      out[idx+w*idy] = tex2D(tex_d,(float)idx/w,(float)idy/h);
                       ^

kernel.cu(99): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
      tex2D(tex,(idx+.5f)/1920,(idy+.5f)/1080)
      ^

kernel.cu(100): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
      -tex2D(tex_d,(idx+ox)/1920,(idy+oy)/1080)
       ^

kernel.cu(101): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
      )*tex2D(texMask,idx+.5f,idy+.5f);
        ^

16 errors detected in the compilation of "kernel.cu".
kernel.cu
]
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
```

I believe that I have the wrong version of CUDA, or Visual Studio?
